# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthur/Documents/IN204

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthur/Documents/IN204

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Documents/IN204/CMakeFiles /home/arthur/Documents/IN204//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Documents/IN204/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Client_sender

# Build rule for target.
Client_sender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client_sender
.PHONY : Client_sender

# fast build rule for target.
Client_sender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_sender.dir/build.make CMakeFiles/Client_sender.dir/build
.PHONY : Client_sender/fast

#=============================================================================
# Target rules for targets named Client_receiver

# Build rule for target.
Client_receiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client_receiver
.PHONY : Client_receiver

# fast build rule for target.
Client_receiver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_receiver.dir/build.make CMakeFiles/Client_receiver.dir/build
.PHONY : Client_receiver/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

source/client_receiver.o: source/client_receiver.cpp.o
.PHONY : source/client_receiver.o

# target to build an object file
source/client_receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_receiver.dir/build.make CMakeFiles/Client_receiver.dir/source/client_receiver.cpp.o
.PHONY : source/client_receiver.cpp.o

source/client_receiver.i: source/client_receiver.cpp.i
.PHONY : source/client_receiver.i

# target to preprocess a source file
source/client_receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_receiver.dir/build.make CMakeFiles/Client_receiver.dir/source/client_receiver.cpp.i
.PHONY : source/client_receiver.cpp.i

source/client_receiver.s: source/client_receiver.cpp.s
.PHONY : source/client_receiver.s

# target to generate assembly for a file
source/client_receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_receiver.dir/build.make CMakeFiles/Client_receiver.dir/source/client_receiver.cpp.s
.PHONY : source/client_receiver.cpp.s

source/client_sender.o: source/client_sender.cpp.o
.PHONY : source/client_sender.o

# target to build an object file
source/client_sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_sender.dir/build.make CMakeFiles/Client_sender.dir/source/client_sender.cpp.o
.PHONY : source/client_sender.cpp.o

source/client_sender.i: source/client_sender.cpp.i
.PHONY : source/client_sender.i

# target to preprocess a source file
source/client_sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_sender.dir/build.make CMakeFiles/Client_sender.dir/source/client_sender.cpp.i
.PHONY : source/client_sender.cpp.i

source/client_sender.s: source/client_sender.cpp.s
.PHONY : source/client_sender.s

# target to generate assembly for a file
source/client_sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client_sender.dir/build.make CMakeFiles/Client_sender.dir/source/client_sender.cpp.s
.PHONY : source/client_sender.cpp.s

source/server.o: source/server.cpp.o
.PHONY : source/server.o

# target to build an object file
source/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/source/server.cpp.o
.PHONY : source/server.cpp.o

source/server.i: source/server.cpp.i
.PHONY : source/server.i

# target to preprocess a source file
source/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/source/server.cpp.i
.PHONY : source/server.cpp.i

source/server.s: source/server.cpp.s
.PHONY : source/server.s

# target to generate assembly for a file
source/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/source/server.cpp.s
.PHONY : source/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Client_receiver"
	@echo "... Client_sender"
	@echo "... Server"
	@echo "... source/client_receiver.o"
	@echo "... source/client_receiver.i"
	@echo "... source/client_receiver.s"
	@echo "... source/client_sender.o"
	@echo "... source/client_sender.i"
	@echo "... source/client_sender.s"
	@echo "... source/server.o"
	@echo "... source/server.i"
	@echo "... source/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

