# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arthur/Documents/IN204

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arthur/Documents/IN204

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Documents/IN204/CMakeFiles /home/arthur/Documents/IN204/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arthur/Documents/IN204/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

source/client.o: source/client.cpp.o

.PHONY : source/client.o

# target to build an object file
source/client.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/source/client.cpp.o
.PHONY : source/client.cpp.o

source/client.i: source/client.cpp.i

.PHONY : source/client.i

# target to preprocess a source file
source/client.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/source/client.cpp.i
.PHONY : source/client.cpp.i

source/client.s: source/client.cpp.s

.PHONY : source/client.s

# target to generate assembly for a file
source/client.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/source/client.cpp.s
.PHONY : source/client.cpp.s

source/server.o: source/server.cpp.o

.PHONY : source/server.o

# target to build an object file
source/server.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/source/server.cpp.o
.PHONY : source/server.cpp.o

source/server.i: source/server.cpp.i

.PHONY : source/server.i

# target to preprocess a source file
source/server.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/source/server.cpp.i
.PHONY : source/server.cpp.i

source/server.s: source/server.cpp.s

.PHONY : source/server.s

# target to generate assembly for a file
source/server.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/source/server.cpp.s
.PHONY : source/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Client"
	@echo "... edit_cache"
	@echo "... Server"
	@echo "... source/client.o"
	@echo "... source/client.i"
	@echo "... source/client.s"
	@echo "... source/server.o"
	@echo "... source/server.i"
	@echo "... source/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

